/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'SpideyPC'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 122 */
struct CCamera
{
  CBody cbody;
  _BYTE gapF4[4];
  char field_F8;
  char field_F9;
  int field_FC;
  char field_100;
  int field_104;
  int field_108;
  int field_10C;
  int field_110;
  int field_114;
  int field_118;
  int field_11C;
  int field_120;
  int field_124;
  int field_128;
  int field_12C;
  int field_130;
  int field_134;
  int field_138;
  int field_13C;
  char field_140;
  int field_144;
  int field_148;
  int field_14C;
  int field_150;
  int field_154;
  int field_158;
  int field_15C;
  int field_160;
  int field_164;
  int field_168;
  int field_16C;
  int field_170;
  _BYTE gap174[52];
  int field_1A8;
  int field_1AC;
  int field_1B0;
  int field_1B4;
  int field_1B8;
  int field_1BC;
  int field_1C0;
  _BYTE gap1C4[4];
  int field_1C8;
  __int16 field_1CC;
  __int16 field_1CE;
  _BYTE gap1D0[8];
  int field_1D8;
  int field_1DC;
  int field_1E0;
  int field_1E4;
  int field_1E8;
  int field_1EC;
  int field_1F0;
  int field_1F4;
  int field_1F8;
  int field_1FC;
  int field_200;
  int field_204;
  int field_208;
  int field_20C;
  int field_210;
  int field_214;
  int field_218;
  int field_21C;
  int field_220;
  int field_224;
  int field_228;
  int field_22C;
  int field_230;
  int field_234;
  __int16 field_238;
  __declspec(align(4)) char field_23C;
  int field_240;
  int field_244;
  int field_248;
  CVector field_24C;
  int field_258;
  int field_25C;
  int field_260;
  int field_264;
  int field_268;
  __int16 field_26C;
  __int16 field_26E;
  _BYTE gap270[4];
  __int16 field_274;
  char field_276;
  char field_277;
  char field_278;
  __int16 field_27A;
  __int16 field_27C;
  __int16 field_27E;
  _BYTE gap280[4];
  int field_284;
  int field_288;
  int field_28C;
  int field_290;
  int field_294;
  int field_298;
  int field_29C;
  int field_2A0;
  int field_2A4;
  int field_2A8;
  char field_2AC;
  int field_2B0;
  int field_2B4;
  int field_2B8;
  int field_2BC;
  int field_2C0;
  int field_2C4;
  int field_2C8;
  int field_2CC;
  int field_2D0;
  CQuat field_2D4;
  __int16 field_2E4;
  CVector field_2E8;
};

