name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-old-win:
    runs-on: windows-2025

    steps:
      - name: Setup Visual Studio
        run: |
          Invoke-WebRequest https://github.com/krystalgamer/spidey-decomp-vs/releases/download/v1.0/spidey-vs.zip -OutFile c:\spidey_vs.zip
          7z x C:\spidey_vs.zip -oC:\vs
      - uses: actions/checkout@v4
      - name: Setup spidey-decomp
        shell: cmd
        run: |
          mkdir C:\spidey-decomp
          xcopy %GITHUB_WORKSPACE% C:\spidey-decomp /s /e
      - name: Build
        shell: cmd
        working-directory: C:\spidey-decomp
        run: build.bat
      - name: Validate
        shell: cmd
        working-directory: C:\spidey-decomp\Release
        run: spider.exe


  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v4
    - name: Install 32-bit libs
      run: sudo apt install g++-multilib
    - name: Setup Makefile
      run: CXX=${{ matrix.compiler }} cmake -B out
    - name: Build
      run: cmake --build out
    - name: Run
      run: ./out/spider

  build-win:
    runs-on: windows-2025
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - uses: actions/checkout@v4
    - name: Generate solution
      run: cmake -B out -A Win32
    - name: Compile
      working-directory: ./out
      run: msbuild spider.sln /p:Platform=Win32 /p:Configuration=Release
    - name: Run
      working-directory: ./out
      run: Release\spider.exe

  build-mac:

    if: false
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Setup Makefile
      run: cmake -B out
    - name: 
      continue-on-error: true
      run: cmake --build out
    - name: Run
      continue-on-error: true
      run: ./out/spider
