name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  validate-repo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: getsentry/action-setup-venv@v2.1.1
      id: venv
      with:
        python-version: 3.12.3
        install-cmd: pip install tree-sitter tree-sitter-cpp
    - name: Run script
      run: python tools/dunno.py


  build-old-win:
    needs: validate-repo
    runs-on: windows-2025

    steps:
      - name: Setup Visual Studio
        run: |
          Invoke-WebRequest https://github.com/krystalgamer/spidey-decomp-vs/releases/download/v1.0/spidey-vs.zip -OutFile c:\spidey_vs.zip
          7z x C:\spidey_vs.zip -oC:\vs
      - uses: actions/checkout@v4
      - name: Build
        shell: cmd
        run: build.bat
      - name: Validate
        shell: cmd
        run: .\Release\spider.exe


  build-linux:
    needs: validate-repo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v4
    - name: Install 32-bit libs
      run: sudo apt install g++-multilib
    - name: Setup Makefile
      run: CXX=${{ matrix.compiler }} cmake -B out
    - name: Build
      run: cmake --build out
    - name: Run
      run: ./out/spider

  build-win:
    needs: validate-repo
    runs-on: windows-2025
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - uses: actions/checkout@v4
    - name: Generate solution
      run: cmake -B out -A Win32
    - name: Compile
      working-directory: ./out
      run: msbuild spider.sln /p:Platform=Win32 /p:Configuration=Release
    - name: Run
      working-directory: ./out
      run: Release\spider.exe

  build-mac:
    if: false
    needs: validate-repo
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Setup Makefile
      run: cmake -B out
    - name: 
      continue-on-error: true
      run: cmake --build out
    - name: Run
      continue-on-error: true
      run: ./out/spider
